[book]
authors = ["Tony Bark"]
language = "en"
multilingual = false
src = "src"
title = "Tony's List of Sims Mods"

[rust]
edition = "2021"

[output.html]
default-theme = "navy"
no-section-label = true
git-repository-url = "https://github.com/tonytins/tsmods"

[output.html.fold]
enable = true

[output.html.search]
enable = true
limit-results = 15